(cl:in-package mmmros-msg)
(cl:export '(LEFTWHEELSPEED-VAL
          LEFTWHEELSPEED
          RIGHTWHEELSPEED-VAL
          RIGHTWHEELSPEED
          LEFTSHOULDERANGLE-VAL
          LEFTSHOULDERANGLE
          RIGHTSHOULDERANGLE-VAL
          RIGHTSHOULDERANGLE
          LEFTELBOWANGLE-VAL
          LEFTELBOWANGLE
          RIGHTELBOWANGLE-VAL
          RIGHTELBOWANGLE
          LEFTARMEXTENSION-VAL
          LEFTARMEXTENSION
          RIGHTARMEXTENSION-VAL
          RIGHTARMEXTENSION
          LEFTGRIPPERANGLES-VAL
          LEFTGRIPPERANGLES
          RIGHTGRIPPERANGLES-VAL
          RIGHTGRIPPERANGLES
))